const city = {
  code: 1,
  mes: "请求成功",
  result: [
    {
      id: 537,
      cityName: "阿勒泰",
      cityId: 175,
      firstLetter: "A",
      airportName: "阿勒泰机场",
    },
    {
      id: 541,
      cityName: "安康",
      cityId: 171,
      firstLetter: "A",
      airportName: "安康富强机场",
    },
    {
      id: 542,
      cityName: "阿克苏",
      cityId: 173,
      firstLetter: "A",
      airportName: "阿克苏机场",
    },
    {
      id: 543,
      cityName: "鞍山",
      cityId: 178,
      firstLetter: "A",
      airportName: "鞍山腾鳌机场",
    },
    {
      id: 544,
      cityName: "安庆",
      cityId: 177,
      firstLetter: "A",
      airportName: "天柱山机场",
    },
    {
      id: 545,
      cityName: "安顺",
      cityId: 179,
      firstLetter: "A",
      airportName: "黄果树机场",
    },
    {
      id: 546,
      cityName: "阿拉善左旗",
      cityId: 21269,
      firstLetter: "A",
      airportName: "阿拉善左旗机场",
    },
    {
      id: 690,
      cityName: "阿里",
      cityId: 97,
      firstLetter: "A",
      airportName: "阿里昆莎机场",
    },
    {
      id: 702,
      cityName: "阿拉善右旗",
      cityId: 21863,
      firstLetter: "A",
      airportName: "阿拉善右旗机场",
    },
    {
      id: 759,
      cityName: "阿尔山",
      cityId: 1658,
      firstLetter: "A",
      airportName: "伊尔施机场",
    },
    {
      id: 539,
      cityName: "百色",
      cityId: 1140,
      firstLetter: "B",
      airportName: "百色机场",
    },
    {
      id: 548,
      cityName: "包头",
      cityId: 141,
      firstLetter: "B",
      airportName: "东河机场",
    },
    {
      id: 549,
      cityName: "毕节",
      cityId: 22031,
      firstLetter: "B",
      airportName: "飞雄机场",
    },
    {
      id: 550,
      cityName: "北海",
      cityId: 189,
      firstLetter: "B",
      airportName: "福成机场",
    },
    {
      id: 552,
      cityName: "博乐",
      cityId: 2548,
      firstLetter: "B",
      airportName: "博乐机场",
    },
    {
      id: 554,
      cityName: "保山",
      cityId: 197,
      firstLetter: "B",
      airportName: "保山机场",
    },
    {
      id: 686,
      cityName: "北京",
      cityId: 1,
      firstLetter: "B",
      airportName: "南苑机场",
    },
    {
      id: 699,
      cityName: "北京",
      cityId: 1,
      firstLetter: "B",
      airportName: "首都国际机场",
    },
    {
      id: 705,
      cityName: "巴彦淖尔",
      cityId: 3887,
      firstLetter: "B",
      airportName: "天吉泰机场",
    },
    {
      id: 2670,
      cityName: "白城",
      cityId: 1116,
      firstLetter: "B",
      airportName: "长安机场",
    },
    {
      id: 4556,
      cityName: "巴中",
      cityId: 3966,
      firstLetter: "B",
      airportName: "恩阳机场",
    },
    {
      id: 6528,
      cityName: "北京",
      cityId: 1,
      firstLetter: "B",
      airportName: "大兴国际机场",
    },
    {
      id: 9246,
      cityName: "滨州",
      cityId: 1820,
      firstLetter: "B",
      airportName: "滨州大高通用机场",
    },
    {
      id: 553,
      cityName: "昌都",
      cityId: 575,
      firstLetter: "C",
      airportName: "昌都邦达机场",
    },
    {
      id: 556,
      cityName: "常德",
      cityId: 201,
      firstLetter: "C",
      airportName: "桃花源机场",
    },
    {
      id: 558,
      cityName: "长春",
      cityId: 158,
      firstLetter: "C",
      airportName: "龙嘉国际机场",
    },
    {
      id: 559,
      cityName: "朝阳",
      cityId: 211,
      firstLetter: "C",
      airportName: "朝阳机场",
    },
    {
      id: 560,
      cityName: "赤峰",
      cityId: 202,
      firstLetter: "C",
      airportName: "玉龙机场",
    },
    {
      id: 561,
      cityName: "长治",
      cityId: 137,
      firstLetter: "C",
      airportName: "长治机场",
    },
    {
      id: 562,
      cityName: "重庆",
      cityId: 4,
      firstLetter: "C",
      airportName: "江北国际机场",
    },
    {
      id: 563,
      cityName: "重庆",
      cityId: 4,
      firstLetter: "C",
      airportName: "江北国际机场",
    },
    {
      id: 565,
      cityName: "长沙",
      cityId: 206,
      firstLetter: "C",
      airportName: "黄花国际机场",
    },
    {
      id: 566,
      cityName: "成都",
      cityId: 28,
      firstLetter: "C",
      airportName: "双流国际机场",
    },
    {
      id: 567,
      cityName: "常州",
      cityId: 213,
      firstLetter: "C",
      airportName: "奔牛国际机场",
    },
    {
      id: 641,
      cityName: "池州",
      cityId: 218,
      firstLetter: "C",
      airportName: "九华山机场",
    },
    {
      id: 687,
      cityName: "长白山",
      cityId: 199,
      firstLetter: "C",
      airportName: "长白山机场",
    },
    {
      id: 4539,
      cityName: "承德",
      cityId: 562,
      firstLetter: "C",
      airportName: "普宁机场",
    },
    {
      id: 4540,
      cityName: "沧源",
      cityId: 21741,
      firstLetter: "C",
      airportName: "佤山机场",
    },
    {
      id: 6535,
      cityName: "赤峰",
      cityId: 202,
      firstLetter: "C",
      airportName: "阿鲁科尔沁机场",
    },
    {
      id: 9250,
      cityName: "成都",
      cityId: 28,
      firstLetter: "C",
      airportName: "天府国际机场",
    },
    {
      id: 568,
      cityName: "大同",
      cityId: 136,
      firstLetter: "D",
      airportName: "大同云冈机场",
    },
    {
      id: 569,
      cityName: "达县",
      cityId: 234,
      firstLetter: "D",
      airportName: "达县机场",
    },
    {
      id: 570,
      cityName: "达州",
      cityId: 234,
      firstLetter: "D",
      airportName: "达县机场",
    },
    {
      id: 571,
      cityName: "稻城",
      cityId: 1222,
      firstLetter: "D",
      airportName: "亚丁机场",
    },
    {
      id: 572,
      cityName: "丹东",
      cityId: 221,
      firstLetter: "D",
      airportName: "浪头机场",
    },
    {
      id: 573,
      cityName: "迪庆",
      cityId: 93,
      firstLetter: "D",
      airportName: "香格里拉机场",
    },
    {
      id: 575,
      cityName: "大连",
      cityId: 6,
      firstLetter: "D",
      airportName: "周水子国际机场",
    },
    {
      id: 576,
      cityName: "大理",
      cityId: 36,
      firstLetter: "D",
      airportName: "大理机场",
    },
    {
      id: 577,
      cityName: "敦煌",
      cityId: 11,
      firstLetter: "D",
      airportName: "敦煌机场",
    },
    {
      id: 578,
      cityName: "东营",
      cityId: 236,
      firstLetter: "D",
      airportName: "胜利机场",
    },
    {
      id: 579,
      cityName: "大庆",
      cityId: 231,
      firstLetter: "D",
      airportName: "萨尔图机场",
    },
    {
      id: 618,
      cityName: "德令哈",
      cityId: 2542,
      firstLetter: "D",
      airportName: "德令哈机场",
    },
    {
      id: 6533,
      cityName: "东阳",
      cityId: 755,
      firstLetter: "D",
      airportName: "东阳横店通用机场",
    },
    {
      id: 9244,
      cityName: "丹凤",
      cityId: 123,
      firstLetter: "D",
      airportName: "丹凤商镇通用机场",
    },
    {
      id: 580,
      cityName: "鄂尔多斯",
      cityId: 3976,
      firstLetter: "E",
      airportName: "鄂尔多斯机场",
    },
    {
      id: 582,
      cityName: "额济纳旗",
      cityId: 21339,
      firstLetter: "E",
      airportName: "桃来机场",
    },
    {
      id: 583,
      cityName: "恩施",
      cityId: 245,
      firstLetter: "E",
      airportName: "许家坪机场",
    },
    {
      id: 585,
      cityName: "二连浩特",
      cityId: 7626,
      firstLetter: "E",
      airportName: "赛乌苏国际机场",
    },
    {
      id: 586,
      cityName: "福州",
      cityId: 258,
      firstLetter: "F",
      airportName: "长乐国际机场",
    },
    {
      id: 587,
      cityName: "阜阳",
      cityId: 257,
      firstLetter: "F",
      airportName: "西关机场",
    },
    {
      id: 588,
      cityName: "佛山",
      cityId: 251,
      firstLetter: "F",
      airportName: "沙堤机场",
    },
    {
      id: 589,
      cityName: "抚远",
      cityId: 21943,
      firstLetter: "F",
      airportName: "东极机场",
    },
    {
      id: 590,
      cityName: "富蕴",
      cityId: 255,
      firstLetter: "F",
      airportName: "富蕴机场",
    },
    {
      id: 555,
      cityName: "广州",
      cityId: 32,
      firstLetter: "G",
      airportName: "新白云国际机场",
    },
    {
      id: 591,
      cityName: "广汉",
      cityId: 750,
      firstLetter: "G",
      airportName: "广汉机场",
    },
    {
      id: 592,
      cityName: "果洛",
      cityId: 21862,
      firstLetter: "G",
      airportName: "玛沁机场",
    },
    {
      id: 593,
      cityName: "格尔木",
      cityId: 132,
      firstLetter: "G",
      airportName: "格尔木机场",
    },
    {
      id: 595,
      cityName: "广元",
      cityId: 267,
      firstLetter: "G",
      airportName: "盘龙机场",
    },
    {
      id: 596,
      cityName: "固原",
      cityId: 321,
      firstLetter: "G",
      airportName: "六盘山机场",
    },
    {
      id: 653,
      cityName: "赣州",
      cityId: 268,
      firstLetter: "G",
      airportName: "黄金机场",
    },
    {
      id: 656,
      cityName: "贵阳",
      cityId: 38,
      firstLetter: "G",
      airportName: "龙洞堡机场",
    },
    {
      id: 657,
      cityName: "桂林",
      cityId: 33,
      firstLetter: "G",
      airportName: "两江国际机场",
    },
    {
      id: 662,
      cityName: "光化",
      cityId: 2155,
      firstLetter: "G",
      airportName: "光化机场",
    },
    {
      id: 6538,
      cityName: "甘孜",
      cityId: 21672,
      firstLetter: "G",
      airportName: "甘孜格萨尔机场",
    },
    {
      id: 540,
      cityName: "红原",
      cityId: 7835,
      firstLetter: "H",
      airportName: "阿坝红原机场",
    },
    {
      id: 597,
      cityName: "海口",
      cityId: 42,
      firstLetter: "H",
      airportName: "美兰机场",
    },
    {
      id: 598,
      cityName: "河池",
      cityId: 3969,
      firstLetter: "H",
      airportName: "金城江机场",
    },
    {
      id: 599,
      cityName: "邯郸",
      cityId: 275,
      firstLetter: "H",
      airportName: "邯郸机场",
    },
    {
      id: 600,
      cityName: "黑河",
      cityId: 281,
      firstLetter: "H",
      airportName: "黑河机场",
    },
    {
      id: 601,
      cityName: "呼和浩特",
      cityId: 103,
      firstLetter: "H",
      airportName: "白塔国际机场",
    },
    {
      id: 602,
      cityName: "合肥",
      cityId: 278,
      firstLetter: "H",
      airportName: "新桥国际机场",
    },
    {
      id: 603,
      cityName: "杭州",
      cityId: 17,
      firstLetter: "H",
      airportName: "萧山国际机场",
    },
    {
      id: 604,
      cityName: "淮安",
      cityId: 577,
      firstLetter: "H",
      airportName: "涟水机场",
    },
    {
      id: 605,
      cityName: "怀化",
      cityId: 282,
      firstLetter: "H",
      airportName: "芷江机场",
    },
    {
      id: 607,
      cityName: "海拉尔",
      cityId: 142,
      firstLetter: "H",
      airportName: "东山机场",
    },
    {
      id: 609,
      cityName: "哈密",
      cityId: 285,
      firstLetter: "H",
      airportName: "哈密机场",
    },
    {
      id: 610,
      cityName: "衡阳",
      cityId: 297,
      firstLetter: "H",
      airportName: "南岳机场",
    },
    {
      id: 612,
      cityName: "哈尔滨",
      cityId: 5,
      firstLetter: "H",
      airportName: "太平国际机场",
    },
    {
      id: 615,
      cityName: "和田",
      cityId: 294,
      firstLetter: "H",
      airportName: "和田机场",
    },
    {
      id: 616,
      cityName: "花土沟",
      cityId: 83679,
      firstLetter: "H",
      airportName: "花土沟机场",
    },
    {
      id: 617,
      cityName: "惠州",
      cityId: 299,
      firstLetter: "H",
      airportName: "平潭机场",
    },
    {
      id: 620,
      cityName: "汉中",
      cityId: 129,
      firstLetter: "H",
      airportName: "城固机场",
    },
    {
      id: 732,
      cityName: "黄山",
      cityId: 23,
      firstLetter: "H",
      airportName: "屯溪机场",
    },
    {
      id: 4544,
      cityName: "呼伦贝尔",
      cityId: 4255,
      firstLetter: "H",
      airportName: "新巴尔虎右旗宝格德机场",
    },
    {
      id: 4546,
      cityName: "霍林郭勒",
      cityId: 21091,
      firstLetter: "H",
      airportName: "霍林河机场",
    },
    {
      id: 6529,
      cityName: "黑河",
      cityId: 281,
      firstLetter: "H",
      airportName: "嫩江墨尔根通用机场",
    },
    {
      id: 6531,
      cityName: "湖州",
      cityId: 86,
      firstLetter: "H",
      airportName: "德清莫干山通用机场",
    },
    {
      id: 9254,
      cityName: "菏泽",
      cityId: 1074,
      firstLetter: "H",
      airportName: "菏泽牡丹机场",
    },
    {
      id: 625,
      cityName: "景德镇",
      cityId: 305,
      firstLetter: "J",
      airportName: "景德镇机场",
    },
    {
      id: 626,
      cityName: "加格达奇",
      cityId: 1143,
      firstLetter: "J",
      airportName: "加格达奇机场",
    },
    {
      id: 627,
      cityName: "嘉峪关",
      cityId: 326,
      firstLetter: "J",
      airportName: "嘉峪关机场",
    },
    {
      id: 628,
      cityName: "井冈山",
      cityId: 307,
      firstLetter: "J",
      airportName: "井冈山机场",
    },
    {
      id: 629,
      cityName: "景洪",
      cityId: 35,
      firstLetter: "J",
      airportName: "西双版纳机场",
    },
    {
      id: 631,
      cityName: "金昌",
      cityId: 1158,
      firstLetter: "J",
      airportName: "金昌金川机场",
    },
    {
      id: 632,
      cityName: "吉林",
      cityId: 159,
      firstLetter: "J",
      airportName: "二台子机场",
    },
    {
      id: 634,
      cityName: "九江",
      cityId: 24,
      firstLetter: "J",
      airportName: "庐山机场",
    },
    {
      id: 635,
      cityName: "晋江",
      cityId: 406,
      firstLetter: "J",
      airportName: "泉州晋江机场",
    },
    {
      id: 638,
      cityName: "佳木斯",
      cityId: 317,
      firstLetter: "J",
      airportName: "东郊机场",
    },
    {
      id: 639,
      cityName: "济宁",
      cityId: 318,
      firstLetter: "J",
      airportName: "曲阜机场",
    },
    {
      id: 640,
      cityName: "锦州",
      cityId: 327,
      firstLetter: "J",
      airportName: "锦州湾机场",
    },
    {
      id: 643,
      cityName: "鸡西",
      cityId: 157,
      firstLetter: "J",
      airportName: "兴凯湖机场",
    },
    {
      id: 644,
      cityName: "九寨沟",
      cityId: 91,
      firstLetter: "J",
      airportName: "黄龙机场",
    },
    {
      id: 652,
      cityName: "金门",
      cityId: 7203,
      firstLetter: "J",
      airportName: "尚义机场",
    },
    {
      id: 715,
      cityName: "揭阳",
      cityId: 956,
      firstLetter: "J",
      airportName: "揭阳潮汕机场",
    },
    {
      id: 727,
      cityName: "济南",
      cityId: 144,
      firstLetter: "J",
      airportName: "遥墙国际机场",
    },
    {
      id: 4547,
      cityName: "建三江",
      cityId: 1623,
      firstLetter: "J",
      airportName: "建三江机场",
    },
    {
      id: 9241,
      cityName: "建德",
      cityId: 658,
      firstLetter: "J",
      airportName: "千岛湖通用机场",
    },
    {
      id: 645,
      cityName: "库车",
      cityId: 329,
      firstLetter: "K",
      airportName: "库车机场",
    },
    {
      id: 646,
      cityName: "康定",
      cityId: 4130,
      firstLetter: "K",
      airportName: "康定机场",
    },
    {
      id: 647,
      cityName: "喀什",
      cityId: 109,
      firstLetter: "K",
      airportName: "喀什机场",
    },
    {
      id: 649,
      cityName: "凯里",
      cityId: 333,
      firstLetter: "K",
      airportName: "黄平机场",
    },
    {
      id: 650,
      cityName: "喀纳斯",
      cityId: 3326,
      firstLetter: "K",
      airportName: "喀纳斯机场",
    },
    {
      id: 651,
      cityName: "昆明",
      cityId: 34,
      firstLetter: "K",
      airportName: "长水国际机场",
    },
    {
      id: 654,
      cityName: "库尔勒",
      cityId: 330,
      firstLetter: "K",
      airportName: "库尔勒机场",
    },
    {
      id: 655,
      cityName: "克拉玛依",
      cityId: 166,
      firstLetter: "K",
      airportName: "克拉玛依机场",
    },
    {
      id: 621,
      cityName: "黎平",
      cityId: 3852,
      firstLetter: "L",
      airportName: "黎平机场",
    },
    {
      id: 658,
      cityName: "连城",
      cityId: 348,
      firstLetter: "L",
      airportName: "冠豸山机场",
    },
    {
      id: 659,
      cityName: "龙岩",
      cityId: 348,
      firstLetter: "L",
      airportName: "冠豸山机场",
    },
    {
      id: 661,
      cityName: "临汾",
      cityId: 139,
      firstLetter: "L",
      airportName: "尧都机场",
    },
    {
      id: 663,
      cityName: "兰州",
      cityId: 100,
      firstLetter: "L",
      airportName: "中川机场",
    },
    {
      id: 664,
      cityName: "梁平",
      cityId: 427,
      firstLetter: "L",
      airportName: "梁平机场",
    },
    {
      id: 665,
      cityName: "丽江",
      cityId: 37,
      firstLetter: "L",
      airportName: "丽江机场",
    },
    {
      id: 666,
      cityName: "荔波",
      cityId: 1708,
      firstLetter: "L",
      airportName: "荔波机场",
    },
    {
      id: 668,
      cityName: "吕梁",
      cityId: 7631,
      firstLetter: "L",
      airportName: "吕梁机场",
    },
    {
      id: 669,
      cityName: "临沧",
      cityId: 1236,
      firstLetter: "L",
      airportName: "临沧机场",
    },
    {
      id: 670,
      cityName: "六盘水",
      cityId: 605,
      firstLetter: "L",
      airportName: "月照机场",
    },
    {
      id: 673,
      cityName: "拉萨",
      cityId: 41,
      firstLetter: "L",
      airportName: "贡嘎机场",
    },
    {
      id: 674,
      cityName: "林西",
      cityId: 744,
      firstLetter: "L",
      airportName: "林西机场",
    },
    {
      id: 675,
      cityName: "洛阳",
      cityId: 350,
      firstLetter: "L",
      airportName: "北郊机场",
    },
    {
      id: 676,
      cityName: "连云港",
      cityId: 353,
      firstLetter: "L",
      airportName: "白塔埠机场",
    },
    {
      id: 677,
      cityName: "临沂",
      cityId: 569,
      firstLetter: "L",
      airportName: "临沂启阳机场",
    },
    {
      id: 678,
      cityName: "柳州",
      cityId: 354,
      firstLetter: "L",
      airportName: "白莲机场",
    },
    {
      id: 679,
      cityName: "泸州",
      cityId: 355,
      firstLetter: "L",
      airportName: "云龙机场",
    },
    {
      id: 680,
      cityName: "林芝",
      cityId: 108,
      firstLetter: "L",
      airportName: "林芝米林机场",
    },
    {
      id: 777,
      cityName: "澜沧",
      cityId: 21596,
      firstLetter: "L",
      airportName: "景迈机场",
    },
    {
      id: 4548,
      cityName: "陇南",
      cityId: 7707,
      firstLetter: "L",
      airportName: "成县机场",
    },
    {
      id: 9248,
      cityName: "陇川",
      cityId: 21525,
      firstLetter: "L",
      airportName: "陇川广宋机场",
    },
    {
      id: 672,
      cityName: "芒市",
      cityId: 3997,
      firstLetter: "M",
      airportName: "德宏芒市机场",
    },
    {
      id: 681,
      cityName: "牡丹江",
      cityId: 150,
      firstLetter: "M",
      airportName: "海浪机场",
    },
    {
      id: 682,
      cityName: "绵阳",
      cityId: 370,
      firstLetter: "M",
      airportName: "南郊机场",
    },
    {
      id: 683,
      cityName: "梅县",
      cityId: 3053,
      firstLetter: "M",
      airportName: "梅县机场",
    },
    {
      id: 684,
      cityName: "梅州",
      cityId: 3053,
      firstLetter: "M",
      airportName: "梅县机场",
    },
    {
      id: 697,
      cityName: "满洲里",
      cityId: 1083,
      firstLetter: "M",
      airportName: "西郊机场",
    },
    {
      id: 698,
      cityName: "漠河",
      cityId: 155,
      firstLetter: "M",
      airportName: "漠河机场",
    },
    {
      id: 9240,
      cityName: "马祖",
      cityId: 7808,
      firstLetter: "M",
      airportName: "马祖北竿机场",
    },
    {
      id: 648,
      cityName: "南昌",
      cityId: 376,
      firstLetter: "N",
      airportName: "昌北国际机场",
    },
    {
      id: 685,
      cityName: "南充",
      cityId: 377,
      firstLetter: "N",
      airportName: "高坪机场",
    },
    {
      id: 689,
      cityName: "宁波",
      cityId: 375,
      firstLetter: "N",
      airportName: "栎社国际机场",
    },
    {
      id: 691,
      cityName: "南京",
      cityId: 12,
      firstLetter: "N",
      airportName: "禄口国际机场",
    },
    {
      id: 692,
      cityName: "宁蒗",
      cityId: 1161,
      firstLetter: "N",
      airportName: "泸沽湖机场",
    },
    {
      id: 693,
      cityName: "那拉提",
      cityId: 3360,
      firstLetter: "N",
      airportName: "那拉提机场",
    },
    {
      id: 694,
      cityName: "南宁",
      cityId: 380,
      firstLetter: "N",
      airportName: "吴圩国际机场",
    },
    {
      id: 695,
      cityName: "南阳",
      cityId: 385,
      firstLetter: "N",
      airportName: "姜营机场",
    },
    {
      id: 696,
      cityName: "南通",
      cityId: 82,
      firstLetter: "N",
      airportName: "兴东机场",
    },
    {
      id: 4549,
      cityName: "南竿",
      cityId: 91804,
      firstLetter: "N",
      airportName: "南竿",
    },
    {
      id: 6541,
      cityName: "怒江",
      cityId: 1806,
      firstLetter: "N",
      airportName: "兰坪丰华通用机场",
    },
    {
      id: 613,
      cityName: "普陀山",
      cityId: 19,
      firstLetter: "P",
      airportName: "普陀山机场",
    },
    {
      id: 701,
      cityName: "攀枝花",
      cityId: 1097,
      firstLetter: "P",
      airportName: "保安营机场",
    },
    {
      id: 716,
      cityName: "普洱",
      cityId: 3996,
      firstLetter: "P",
      airportName: "思茅机场",
    },
    {
      id: 547,
      cityName: "琼海",
      cityId: 52,
      firstLetter: "Q",
      airportName: "博鳌机场",
    },
    {
      id: 551,
      cityName: "秦皇岛",
      cityId: 147,
      firstLetter: "Q",
      airportName: "北戴河机场",
    },
    {
      id: 623,
      cityName: "且末",
      cityId: 399,
      firstLetter: "Q",
      airportName: "且末机场",
    },
    {
      id: 624,
      cityName: "庆阳",
      cityId: 404,
      firstLetter: "Q",
      airportName: "庆阳机场",
    },
    {
      id: 633,
      cityName: "黔江",
      cityId: 7708,
      firstLetter: "Q",
      airportName: "黔江武陵山机场",
    },
    {
      id: 636,
      cityName: "泉州",
      cityId: 406,
      firstLetter: "Q",
      airportName: "泉州晋江机场",
    },
    {
      id: 642,
      cityName: "衢州",
      cityId: 407,
      firstLetter: "Q",
      airportName: "衢州机场",
    },
    {
      id: 688,
      cityName: "齐齐哈尔",
      cityId: 149,
      firstLetter: "Q",
      airportName: "三家子机场",
    },
    {
      id: 720,
      cityName: "青岛",
      cityId: 7,
      firstLetter: "Q",
      airportName: "胶东国际机场",
    },
    {
      id: 4552,
      cityName: "祁连",
      cityId: 20892,
      firstLetter: "Q",
      airportName: "海北机场",
    },
    {
      id: 703,
      cityName: "日照",
      cityId: 1106,
      firstLetter: "R",
      airportName: "山字河机场",
    },
    {
      id: 704,
      cityName: "日喀则",
      cityId: 92,
      firstLetter: "R",
      airportName: "日喀则和平机场",
    },
    {
      id: 4551,
      cityName: "若羌",
      cityId: 21737,
      firstLetter: "R",
      airportName: "楼兰机场",
    },
    {
      id: 611,
      cityName: "神农架",
      cityId: 657,
      firstLetter: "S",
      airportName: "红坪机场",
    },
    {
      id: 637,
      cityName: "石狮",
      cityId: 406,
      firstLetter: "S",
      airportName: "泉州晋江机场",
    },
    {
      id: 700,
      cityName: "上海",
      cityId: 2,
      firstLetter: "S",
      airportName: "浦东国际机场",
    },
    {
      id: 706,
      cityName: "上海",
      cityId: 2,
      firstLetter: "S",
      airportName: "虹桥国际机场",
    },
    {
      id: 707,
      cityName: "沈阳",
      cityId: 451,
      firstLetter: "S",
      airportName: "桃仙国际机场",
    },
    {
      id: 708,
      cityName: "石河子",
      cityId: 426,
      firstLetter: "S",
      airportName: "花园机场",
    },
    {
      id: 711,
      cityName: "沙市",
      cityId: 328,
      firstLetter: "S",
      airportName: "沙市机场",
    },
    {
      id: 712,
      cityName: "石家庄",
      cityId: 428,
      firstLetter: "S",
      airportName: "正定国际机场",
    },
    {
      id: 713,
      cityName: "三明",
      cityId: 437,
      firstLetter: "S",
      airportName: "沙县机场",
    },
    {
      id: 717,
      cityName: "思茅",
      cityId: 3996,
      firstLetter: "S",
      airportName: "思茅机场",
    },
    {
      id: 718,
      cityName: "三亚",
      cityId: 43,
      firstLetter: "S",
      airportName: "凤凰国际机场",
    },
    {
      id: 719,
      cityName: "深圳",
      cityId: 30,
      firstLetter: "S",
      airportName: "宝安国际机场",
    },
    {
      id: 737,
      cityName: "十堰",
      cityId: 452,
      firstLetter: "S",
      airportName: "武当山机场",
    },
    {
      id: 2672,
      cityName: "上饶",
      cityId: 411,
      firstLetter: "S",
      airportName: "三清山机场",
    },
    {
      id: 4542,
      cityName: "邵阳",
      cityId: 1111,
      firstLetter: "S",
      airportName: "武冈机场",
    },
    {
      id: 4545,
      cityName: "松原",
      cityId: 1303,
      firstLetter: "S",
      airportName: "查干湖机场",
    },
    {
      id: 4550,
      cityName: "莎车",
      cityId: 21827,
      firstLetter: "S",
      airportName: "莎车机场",
    },
    {
      id: 6542,
      cityName: "石家庄",
      cityId: 428,
      firstLetter: "S",
      airportName: "栾城通用机场",
    },
    {
      id: 619,
      cityName: "台州",
      cityId: 578,
      firstLetter: "T",
      airportName: "路桥机场",
    },
    {
      id: 721,
      cityName: "塔城",
      cityId: 455,
      firstLetter: "T",
      airportName: "塔城民航机场",
    },
    {
      id: 722,
      cityName: "腾冲",
      cityId: 1819,
      firstLetter: "T",
      airportName: "腾冲机场",
    },
    {
      id: 723,
      cityName: "铜仁",
      cityId: 1227,
      firstLetter: "T",
      airportName: "铜仁凤凰机场",
    },
    {
      id: 724,
      cityName: "通辽",
      cityId: 458,
      firstLetter: "T",
      airportName: "通辽机场",
    },
    {
      id: 725,
      cityName: "天水",
      cityId: 464,
      firstLetter: "T",
      airportName: "天水机场",
    },
    {
      id: 726,
      cityName: "吐鲁番",
      cityId: 21811,
      firstLetter: "T",
      airportName: "吐鲁番机场",
    },
    {
      id: 728,
      cityName: "通化",
      cityId: 456,
      firstLetter: "T",
      airportName: "三源浦机场",
    },
    {
      id: 729,
      cityName: "天津",
      cityId: 3,
      firstLetter: "T",
      airportName: "滨海国际机场",
    },
    {
      id: 730,
      cityName: "台东",
      cityId: 3848,
      firstLetter: "T",
      airportName: "台东机场",
    },
    {
      id: 731,
      cityName: "唐山",
      cityId: 468,
      firstLetter: "T",
      airportName: "三女河机场",
    },
    {
      id: 733,
      cityName: "太原",
      cityId: 105,
      firstLetter: "T",
      airportName: "武宿国际机场",
    },
    {
      id: 4555,
      cityName: "图木舒克",
      cityId: 21888,
      firstLetter: "T",
      airportName: "唐王城机场",
    },
    {
      id: 6530,
      cityName: "太原",
      cityId: 105,
      firstLetter: "T",
      airportName: "太原尧城通用机场",
    },
    {
      id: 608,
      cityName: "乌兰浩特",
      cityId: 484,
      firstLetter: "W",
      airportName: "乌兰浩特机场",
    },
    {
      id: 734,
      cityName: "乌兰察布",
      cityId: 7518,
      firstLetter: "W",
      airportName: "乌兰察布机场",
    },
    {
      id: 735,
      cityName: "乌鲁木齐",
      cityId: 39,
      firstLetter: "W",
      airportName: "地窝堡国际机场",
    },
    {
      id: 738,
      cityName: "潍坊",
      cityId: 475,
      firstLetter: "W",
      airportName: "潍坊机场",
    },
    {
      id: 739,
      cityName: "威海",
      cityId: 479,
      firstLetter: "W",
      airportName: "大水泊国际机场",
    },
    {
      id: 740,
      cityName: "文山",
      cityId: 1342,
      firstLetter: "W",
      airportName: "文山普者黑机场",
    },
    {
      id: 741,
      cityName: "温州",
      cityId: 491,
      firstLetter: "W",
      airportName: "温州龙湾国际机场",
    },
    {
      id: 742,
      cityName: "乌海",
      cityId: 1133,
      firstLetter: "W",
      airportName: "乌海机场",
    },
    {
      id: 743,
      cityName: "武汉",
      cityId: 477,
      firstLetter: "W",
      airportName: "天河国际机场",
    },
    {
      id: 744,
      cityName: "武夷山",
      cityId: 26,
      firstLetter: "W",
      airportName: "武夷山机场",
    },
    {
      id: 746,
      cityName: "无锡",
      cityId: 13,
      firstLetter: "W",
      airportName: "无锡硕放机场",
    },
    {
      id: 747,
      cityName: "梧州",
      cityId: 492,
      firstLetter: "W",
      airportName: "西江机场",
    },
    {
      id: 748,
      cityName: "万州",
      cityId: 487,
      firstLetter: "W",
      airportName: "五桥机场",
    },
    {
      id: 4541,
      cityName: "五大连池",
      cityId: 473,
      firstLetter: "W",
      airportName: "德都机场",
    },
    {
      id: 4543,
      cityName: "乌拉特中旗",
      cityId: 21184,
      firstLetter: "W",
      airportName: "乌拉特中旗机场",
    },
    {
      id: 6536,
      cityName: "巫山",
      cityId: 684995,
      firstLetter: "W",
      airportName: "重庆巫山机场",
    },
    {
      id: 9249,
      cityName: "芜湖",
      cityId: 478,
      firstLetter: "W",
      airportName: "芜湖宣州机场",
    },
    {
      id: 9252,
      cityName: "武隆",
      cityId: 21259,
      firstLetter: "W",
      airportName: "重庆仙女山机场",
    },
    {
      id: 538,
      cityName: "兴义",
      cityId: 1139,
      firstLetter: "X",
      airportName: "兴义机场",
    },
    {
      id: 574,
      cityName: "香格里拉",
      cityId: 93,
      firstLetter: "X",
      airportName: "香格里拉机场",
    },
    {
      id: 594,
      cityName: "夏河",
      cityId: 497,
      firstLetter: "X",
      airportName: "夏河机场",
    },
    {
      id: 630,
      cityName: "西双版纳",
      cityId: 35,
      firstLetter: "X",
      airportName: "西双版纳机场",
    },
    {
      id: 745,
      cityName: "忻州",
      cityId: 513,
      firstLetter: "X",
      airportName: "五台山机场",
    },
    {
      id: 749,
      cityName: "襄阳",
      cityId: 496,
      firstLetter: "X",
      airportName: "刘集机场",
    },
    {
      id: 750,
      cityName: "西昌",
      cityId: 494,
      firstLetter: "X",
      airportName: "青山机场",
    },
    {
      id: 751,
      cityName: "锡林浩特",
      cityId: 500,
      firstLetter: "X",
      airportName: "锡林浩特机场",
    },
    {
      id: 752,
      cityName: "西安",
      cityId: 10,
      firstLetter: "X",
      airportName: "咸阳国际机场",
    },
    {
      id: 753,
      cityName: "厦门",
      cityId: 25,
      firstLetter: "X",
      airportName: "高崎国际机场",
    },
    {
      id: 754,
      cityName: "西宁",
      cityId: 124,
      firstLetter: "X",
      airportName: "曹家堡机场",
    },
    {
      id: 755,
      cityName: "徐州",
      cityId: 512,
      firstLetter: "X",
      airportName: "观音机场",
    },
    {
      id: 4553,
      cityName: "信阳",
      cityId: 510,
      firstLetter: "X",
      airportName: "明港机场",
    },
    {
      id: 584,
      cityName: "延安",
      cityId: 110,
      firstLetter: "Y",
      airportName: "南泥湾机场",
    },
    {
      id: 622,
      cityName: "银川",
      cityId: 99,
      firstLetter: "Y",
      airportName: "河东机场",
    },
    {
      id: 660,
      cityName: "伊春",
      cityId: 517,
      firstLetter: "Y",
      airportName: "林都机场",
    },
    {
      id: 667,
      cityName: "永州",
      cityId: 970,
      firstLetter: "Y",
      airportName: "零陵机场",
    },
    {
      id: 736,
      cityName: "榆林",
      cityId: 527,
      firstLetter: "Y",
      airportName: "榆阳机场",
    },
    {
      id: 756,
      cityName: "宜宾",
      cityId: 514,
      firstLetter: "Y",
      airportName: "五粮液机场",
    },
    {
      id: 757,
      cityName: "运城",
      cityId: 140,
      firstLetter: "Y",
      airportName: "张孝机场",
    },
    {
      id: 758,
      cityName: "宜春",
      cityId: 518,
      firstLetter: "Y",
      airportName: "明月山机场",
    },
    {
      id: 760,
      cityName: "宜昌",
      cityId: 515,
      firstLetter: "Y",
      airportName: "三峡机场",
    },
    {
      id: 761,
      cityName: "伊宁",
      cityId: 529,
      firstLetter: "Y",
      airportName: "伊宁机场",
    },
    {
      id: 762,
      cityName: "义乌",
      cityId: 536,
      firstLetter: "Y",
      airportName: "义乌机场",
    },
    {
      id: 763,
      cityName: "营口",
      cityId: 1300,
      firstLetter: "Y",
      airportName: "兰旗机场",
    },
    {
      id: 764,
      cityName: "延吉",
      cityId: 523,
      firstLetter: "Y",
      airportName: "朝阳川国际机场",
    },
    {
      id: 765,
      cityName: "烟台",
      cityId: 533,
      firstLetter: "Y",
      airportName: "蓬莱国际机场",
    },
    {
      id: 766,
      cityName: "盐城",
      cityId: 1200,
      firstLetter: "Y",
      airportName: "南洋国际机场",
    },
    {
      id: 767,
      cityName: "扬州",
      cityId: 15,
      firstLetter: "Y",
      airportName: "扬州泰州机场",
    },
    {
      id: 768,
      cityName: "玉树",
      cityId: 7582,
      firstLetter: "Y",
      airportName: "玉树巴塘机场",
    },
    {
      id: 4554,
      cityName: "岳阳",
      cityId: 539,
      firstLetter: "Y",
      airportName: "三荷机场",
    },
    {
      id: 9243,
      cityName: "玉林",
      cityId: 1113,
      firstLetter: "Y",
      airportName: "玉林福绵机场",
    },
    {
      id: 9247,
      cityName: "于田",
      cityId: 21736,
      firstLetter: "Y",
      airportName: "于田万方机场",
    },
    {
      id: 557,
      cityName: "郑州",
      cityId: 559,
      firstLetter: "Z",
      airportName: "新郑国际机场",
    },
    {
      id: 564,
      cityName: "重庆",
      cityId: 4,
      firstLetter: "Z",
      airportName: "江北国际机场",
    },
    {
      id: 581,
      cityName: "张家界",
      cityId: 27,
      firstLetter: "Z",
      airportName: "荷花机场",
    },
    {
      id: 606,
      cityName: "芷江",
      cityId: 282,
      firstLetter: "Z",
      airportName: "芷江机场",
    },
    {
      id: 614,
      cityName: "舟山",
      cityId: 19,
      firstLetter: "Z",
      airportName: "普陀山机场",
    },
    {
      id: 769,
      cityName: "张掖",
      cityId: 663,
      firstLetter: "Z",
      airportName: "张掖机场",
    },
    {
      id: 770,
      cityName: "昭通",
      cityId: 555,
      firstLetter: "Z",
      airportName: "昭通机场",
    },
    {
      id: 771,
      cityName: "中山",
      cityId: 553,
      firstLetter: "Z",
      airportName: "中山机场",
    },
    {
      id: 772,
      cityName: "湛江",
      cityId: 547,
      firstLetter: "Z",
      airportName: "湛江机场",
    },
    {
      id: 773,
      cityName: "中卫",
      cityId: 556,
      firstLetter: "Z",
      airportName: "中卫机场",
    },
    {
      id: 774,
      cityName: "张家口",
      cityId: 550,
      firstLetter: "Z",
      airportName: "张家口机场",
    },
    {
      id: 775,
      cityName: "珠海",
      cityId: 31,
      firstLetter: "Z",
      airportName: "金湾机场",
    },
    {
      id: 776,
      cityName: "遵义",
      cityId: 558,
      firstLetter: "Z",
      airportName: "新舟机场",
    },
    {
      id: 2671,
      cityName: "扎兰屯",
      cityId: 1135,
      firstLetter: "Z",
      airportName: "成吉思汗机场",
    },
    {
      id: 4538,
      cityName: "遵义",
      cityId: 558,
      firstLetter: "Z",
      airportName: "茅台机场",
    },
    {
      id: 6540,
      cityName: "郑州",
      cityId: 559,
      firstLetter: "Z",
      airportName: "上街机场",
    },
  ],
};
export default city
